import{useState,useEffect}from'react';import{Card,CardContent}from'@/components/ui/card';import{Button}from'@/components/ui/button';import{Input}from'@/components/ui/input';import{Badge}from'@/components/ui/badge';import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from'@/components/ui/select';import{Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter}from'@/components/ui/dialog';import{Label}from'@/components/ui/label';import{Textarea}from'@/components/ui/textarea';import{Truck,Plus,Pencil,Trash2,Search,Loader2,Wrench,DollarSign,Package,Activity,CheckCircle2}from'lucide-react';import{toast}from'sonner';import{api}from'@/api';
const S:Record<string,{l:string,c:string}>={available:{l:'Disponivel',c:'bg-green-100 text-green-800'},rented:{l:'Locado',c:'bg-blue-100 text-blue-800'},maintenance:{l:'Manutencao',c:'bg-orange-100 text-orange-800'},inactive:{l:'Inativo',c:'bg-gray-100 text-gray-600'}};
const C:Record<string,string>={munck:'Munck',generator:'Gerador',excavator:'Retroescavadeira',crane:'Guindaste',truck:'Caminhao',other:'Outro'};
const RS:Record<string,{l:string,c:string}>={draft:{l:'Rascunho',c:'bg-gray-100 text-gray-700'},quoted:{l:'Cotado',c:'bg-yellow-100 text-yellow-800'},confirmed:{l:'Confirmado',c:'bg-blue-100 text-blue-800'},active:{l:'Ativo',c:'bg-green-100 text-green-800'},completed:{l:'Concluido',c:'bg-emerald-100 text-emerald-800'},cancelled:{l:'Cancelado',c:'bg-red-100 text-red-800'}};
const MS:Record<string,{l:string,c:string}>={scheduled:{l:'Agendado',c:'bg-yellow-100 text-yellow-800'},in_progress:{l:'Em Andamento',c:'bg-blue-100 text-blue-800'},completed:{l:'Concluido',c:'bg-green-100 text-green-800'}};
const fmt=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fD=(d:any)=>d?new Date(d).toLocaleDateString('pt-BR'):'-';
export default function EquipmentPage(){
const[tab,setTab]=useState<'dash'|'equip'|'rent'|'maint'>('dash');
const[equipment,setEquipment]=useState<any[]>([]);const[rentals,setRentals]=useState<any[]>([]);const[maints,setMaints]=useState<any[]>([]);
const[clients,setClients]=useState<any[]>([]);const[employees,setEmployees]=useState<any[]>([]);const[stats,setStats]=useState<any>(null);
const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');
const[eqDlg,setEqDlg]=useState(false);const[rentDlg,setRentDlg]=useState(false);const[maintDlg,setMaintDlg]=useState(false);const[editId,setEditId]=useState<string|null>(null);
const[ef,setEf]=useState({name:'',description:'',type:'mobile',category:'munck',brand:'',model:'',year:'',plate:'',serialNumber:'',chassisNumber:'',hourlyRate:'',dailyRate:'',monthlyRate:'',location:'',notes:''});
const[rf,setRf]=useState({equipmentId:'',clientId:'',operatorId:'',operatorName:'',rentalType:'with_operator',billingType:'daily',unitRate:'',quantity:'1',startDate:'',endDate:'',deliveryAddress:'',deliveryCity:'',deliveryState:'',notes:''});
const[mf,setMf]=useState({equipmentId:'',type:'preventive',description:'',cost:'',performedBy:'',performedAt:'',nextDueDate:'',status:'scheduled',notes:''});
useEffect(()=>{ld();},[]);
async function ld(){try{setLoading(true);const[eq,re,ma,st]=await Promise.all([api.getEquipment(),api.getEquipmentRentals().catch(()=>[]),api.getEquipmentMaintenance().catch(()=>[]),api.getEquipmentStats().catch(()=>null)]);setEquipment(eq||[]);setRentals(re||[]);setMaints(ma||[]);setStats(st);try{const[cl,em]=await Promise.all([api.getClients(),api.getEmployees()]);setClients(cl||[]);setEmployees(em||[]);}catch{}}catch(e:any){console.error(e);toast.error('Erro ao carregar');}finally{setLoading(false);}}
async function saveEq(){try{const d={...ef,hourlyRate:Number(ef.hourlyRate)||0,dailyRate:Number(ef.dailyRate)||0,monthlyRate:Number(ef.monthlyRate)||0};if(!d.name){toast.error('Nome obrigatorio');return;}if(editId){await api.updateEquipment(editId,d);}else{await api.createEquipment(d);}toast.success(editId?'Atualizado':'Cadastrado');setEqDlg(false);setEditId(null);resetEf();ld();}catch{toast.error('Erro');}}
function resetEf(){setEf({name:'',description:'',type:'mobile',category:'munck',brand:'',model:'',year:'',plate:'',serialNumber:'',chassisNumber:'',hourlyRate:'',dailyRate:'',monthlyRate:'',location:'',notes:''});}
function editEq(e:any){setEditId(e.id);setEf({name:e.name||'',description:e.description||'',type:e.type||'mobile',category:e.category||'munck',brand:e.brand||'',model:e.model||'',year:e.year||'',plate:e.plate||'',serialNumber:e.serialNumber||'',chassisNumber:e.chassisNumber||'',hourlyRate:String(e.hourlyRate||''),dailyRate:String(e.dailyRate||''),monthlyRate:String(e.monthlyRate||''),location:e.location||'',notes:e.notes||''});setEqDlg(true);}
async function delEq(id:string){if(!confirm('Excluir?'))return;try{await api.deleteEquipment(id);toast.success('Excluido');ld();}catch{toast.error('Erro');}}
async function saveRent(){try{const tv=Number(rf.unitRate||0)*Number(rf.quantity||1);const d={...rf,unitRate:Number(rf.unitRate)||0,quantity:Number(rf.quantity)||1,totalValue:tv,status:'draft'};if(!d.equipmentId){toast.error('Selecione equipamento');return;}await api.createEquipmentRental(d);toast.success('Locacao criada');setRentDlg(false);ld();}catch{toast.error('Erro');}}
async function updRS(id:string,s:string){try{await api.updateEquipmentRentalStatus(id,s);toast.success('Status atualizado');ld();}catch{toast.error('Erro');}}
async function saveMaint(){try{const d={...mf,cost:Number(mf.cost)||0};if(!d.equipmentId||!d.description){toast.error('Campos obrigatorios');return;}await api.createEquipmentMaintenance(d);toast.success('Registrada');setMaintDlg(false);ld();}catch{toast.error('Erro');}}
const fil=equipment.filter(e=>!search||e.name?.toLowerCase().includes(search.toLowerCase())||e.code?.toLowerCase().includes(search.toLowerCase()));
if(loading)return<div className='flex items-center justify-center h-64'><Loader2 className='h-8 w-8 animate-spin text-blue-500'/></div>;
return(<div className='space-y-6'>
<div className='flex items-center justify-between'><div><h1 className='text-2xl font-bold flex items-center gap-2'><Truck className='h-7 w-7 text-orange-500'/>Locacao de Equipamentos</h1><p className='text-sm text-muted-foreground'>Gestao de equipamentos, locacoes e manutencoes</p></div></div>
<div className='flex gap-1 bg-muted/50 p-1 rounded-lg w-fit'>{(['dash','equip','rent','maint'] as const).map(k=>{const lb={dash:'Dashboard',equip:'Equipamentos',rent:'Locacoes',maint:'Manutencoes'}[k];return<button key={k} onClick={()=>setTab(k)} className={'px-4 py-2 rounded-md text-sm font-medium transition-colors '+(tab===k?'bg-white shadow text-foreground':'text-muted-foreground hover:text-foreground')}>{lb}</button>})}</div>
{tab==='dash'&&stats&&<div className='grid grid-cols-1 md:grid-cols-4 gap-4'>
<Card className='border-l-4 border-l-blue-500'><CardContent className='pt-4 pb-4'><div className='flex items-center justify-between'><div><p className='text-sm text-muted-foreground'>Total Equipamentos</p><p className='text-3xl font-bold text-blue-600'>{stats.totalEquipment}</p></div><Package className='h-10 w-10 text-blue-200'/></div></CardContent></Card>
<Card className='border-l-4 border-l-green-500'><CardContent className='pt-4 pb-4'><div className='flex items-center justify-between'><div><p className='text-sm text-muted-foreground'>Disponiveis</p><p className='text-3xl font-bold text-green-600'>{stats.available}</p></div><CheckCircle2 className='h-10 w-10 text-green-200'/></div></CardContent></Card>
<Card className='border-l-4 border-l-orange-500'><CardContent className='pt-4 pb-4'><div className='flex items-center justify-between'><div><p className='text-sm text-muted-foreground'>Locados</p><p className='text-3xl font-bold text-orange-600'>{stats.rented}</p></div><Activity className='h-10 w-10 text-orange-200'/></div></CardContent></Card>
<Card className='border-l-4 border-l-emerald-500'><CardContent className='pt-4 pb-4'><div className='flex items-center justify-between'><div><p className='text-sm text-muted-foreground'>Receita Mensal</p><p className='text-2xl font-bold text-emerald-600'>{fmt(stats.monthlyRevenue)}</p></div><DollarSign className='h-10 w-10 text-emerald-200'/></div></CardContent></Card>
</div>}
{tab==='dash'&&!stats&&<Card className='p-8 text-center'><p className='text-muted-foreground'>Cadastre equipamentos para ver o dashboard</p></Card>}
{tab==='equip'&&<><div className='flex gap-3 items-center'><div className='relative flex-1'><Search className='absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground'/><Input placeholder='Buscar...' value={search} onChange={e=>setSearch(e.target.value)} className='pl-9'/></div><Button onClick={()=>{resetEf();setEditId(null);setEqDlg(true);}}><Plus className='h-4 w-4 mr-1'/>Novo Equipamento</Button></div>
<div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4'>{fil.map(eq=><Card key={eq.id} className='hover:shadow-md transition-shadow'><CardContent className='pt-4'><div className='flex items-start justify-between mb-2'><div><p className='font-semibold'>{eq.name}</p><p className='text-xs text-muted-foreground'>{eq.code} - {C[eq.category]||eq.category}</p></div><Badge className={S[eq.status]?.c||''}>{S[eq.status]?.l||eq.status}</Badge></div>
{eq.brand&&<p className='text-sm text-muted-foreground'>{eq.brand} {eq.model} {eq.year}</p>}{eq.plate&&<p className='text-sm'>Placa: {eq.plate}</p>}
<div className='grid grid-cols-3 gap-2 mt-3 text-center'><div className='bg-muted/50 rounded p-2'><p className='text-xs text-muted-foreground'>Hora</p><p className='text-sm font-medium'>{fmt(eq.hourlyRate)}</p></div><div className='bg-muted/50 rounded p-2'><p className='text-xs text-muted-foreground'>Dia</p><p className='text-sm font-medium'>{fmt(eq.dailyRate)}</p></div><div className='bg-muted/50 rounded p-2'><p className='text-xs text-muted-foreground'>Mes</p><p className='text-sm font-medium'>{fmt(eq.monthlyRate)}</p></div></div>
<div className='flex gap-1 mt-3 justify-end'><Button variant='ghost' size='icon' className='h-8 w-8' onClick={()=>editEq(eq)}><Pencil className='h-4 w-4'/></Button><Button variant='ghost' size='icon' className='h-8 w-8 text-red-500' onClick={()=>delEq(eq.id)}><Trash2 className='h-4 w-4'/></Button></div></CardContent></Card>)}
{fil.length===0&&<Card className='col-span-full p-8 text-center'><Truck className='h-12 w-12 mx-auto mb-2 text-muted-foreground'/><p className='text-muted-foreground'>Nenhum equipamento</p></Card>}</div></>}
{tab==='rent'&&<><div className='flex justify-end'><Button onClick={()=>setRentDlg(true)}><Plus className='h-4 w-4 mr-1'/>Nova Locacao</Button></div><Card><div className='divide-y'>{rentals.map(r=><div key={r.id} className='flex items-center gap-4 px-4 py-3 hover:bg-muted/30'><div className='flex-1 min-w-0'><div className='flex items-center gap-2'><span className='font-medium text-sm'>{r.code}</span><Badge className={RS[r.status]?.c||''}>{RS[r.status]?.l||r.status}</Badge></div><p className='text-xs text-muted-foreground'>{r.equipment?.name||'-'} - {r.client?.name||'Sem cliente'}</p><p className='text-xs text-muted-foreground'>{fD(r.startDate)} a {fD(r.endDate)} - {r.rentalType==='with_operator'?'Com operador':'Sem operador'}</p></div><div className='text-right shrink-0'><p className='font-semibold text-sm'>{fmt(r.totalValue)}</p><div className='flex gap-1 mt-1'>{r.status==='draft'&&<Button size='sm' variant='outline' onClick={()=>updRS(r.id,'confirmed')}>Confirmar</Button>}{r.status==='confirmed'&&<Button size='sm' variant='outline' onClick={()=>updRS(r.id,'active')}>Ativar</Button>}{r.status==='active'&&<Button size='sm' variant='outline' onClick={()=>updRS(r.id,'completed')}>Concluir</Button>}</div></div></div>)}{rentals.length===0&&<div className='p-8 text-center text-muted-foreground'>Nenhuma locacao</div>}</div></Card></>}
{tab==='maint'&&<><div className='flex justify-end'><Button onClick={()=>setMaintDlg(true)}><Plus className='h-4 w-4 mr-1'/>Nova Manutencao</Button></div><Card><div className='divide-y'>{maints.map(m=><div key={m.id} className='flex items-center gap-4 px-4 py-3 hover:bg-muted/30'><Wrench className={'h-5 w-5 '+(m.status==='completed'?'text-green-500':m.status==='in_progress'?'text-blue-500':'text-yellow-500')}/><div className='flex-1'><p className='font-medium text-sm'>{m.description}</p><p className='text-xs text-muted-foreground'>{m.equipment?.name||'-'} - {m.type==='preventive'?'Preventiva':m.type==='corrective'?'Corretiva':'Inspecao'} - {fD(m.performedAt)}</p></div><Badge className={MS[m.status]?.c||''}>{MS[m.status]?.l||m.status}</Badge><span className='text-sm font-medium'>{fmt(m.cost)}</span></div>)}{maints.length===0&&<div className='p-8 text-center text-muted-foreground'>Nenhuma manutencao</div>}</div></Card></>}
<Dialog open={eqDlg} onOpenChange={v=>{if(!v){setEqDlg(false);setEditId(null);}}}><DialogContent className='max-w-2xl max-h-[85vh] overflow-y-auto'><DialogHeader><DialogTitle>{editId?'Editar':'Novo'} Equipamento</DialogTitle></DialogHeader><div className='grid grid-cols-2 gap-3'>
<div className='col-span-2'><Label>Nome *</Label><Input value={ef.name} onChange={e=>setEf({...ef,name:e.target.value})} placeholder='Ex: Munck 12t Madal'/></div>
<div><Label>Tipo</Label><Select value={ef.type} onValueChange={v=>setEf({...ef,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='mobile'>Movel</SelectItem><SelectItem value='stationary'>Estacionario</SelectItem></SelectContent></Select></div>
<div><Label>Categoria</Label><Select value={ef.category} onValueChange={v=>setEf({...ef,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(C).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div>
<div><Label>Marca</Label><Input value={ef.brand} onChange={e=>setEf({...ef,brand:e.target.value})}/></div>
<div><Label>Modelo</Label><Input value={ef.model} onChange={e=>setEf({...ef,model:e.target.value})}/></div>
<div><Label>Ano</Label><Input value={ef.year} onChange={e=>setEf({...ef,year:e.target.value})}/></div>
<div><Label>Placa</Label><Input value={ef.plate} onChange={e=>setEf({...ef,plate:e.target.value})}/></div>
<div><Label>N Serie</Label><Input value={ef.serialNumber} onChange={e=>setEf({...ef,serialNumber:e.target.value})}/></div>
<div><Label>Chassi</Label><Input value={ef.chassisNumber} onChange={e=>setEf({...ef,chassisNumber:e.target.value})}/></div>
<div><Label>R$/Hora</Label><Input type='number' value={ef.hourlyRate} onChange={e=>setEf({...ef,hourlyRate:e.target.value})}/></div>
<div><Label>R$/Dia</Label><Input type='number' value={ef.dailyRate} onChange={e=>setEf({...ef,dailyRate:e.target.value})}/></div>
<div><Label>R$/Mes</Label><Input type='number' value={ef.monthlyRate} onChange={e=>setEf({...ef,monthlyRate:e.target.value})}/></div>
<div><Label>Localizacao</Label><Input value={ef.location} onChange={e=>setEf({...ef,location:e.target.value})}/></div>
<div className='col-span-2'><Label>Obs</Label><Textarea value={ef.notes} onChange={e=>setEf({...ef,notes:e.target.value})} rows={2}/></div>
</div><DialogFooter><Button variant='outline' onClick={()=>{setEqDlg(false);setEditId(null);}}>Cancelar</Button><Button onClick={saveEq}>{editId?'Salvar':'Cadastrar'}</Button></DialogFooter></DialogContent></Dialog>
<Dialog open={rentDlg} onOpenChange={setRentDlg}><DialogContent className='max-w-2xl max-h-[85vh] overflow-y-auto'><DialogHeader><DialogTitle>Nova Locacao</DialogTitle></DialogHeader><div className='grid grid-cols-2 gap-3'>
<div className='col-span-2'><Label>Equipamento *</Label><Select value={rf.equipmentId} onValueChange={v=>setRf({...rf,equipmentId:v})}><SelectTrigger><SelectValue placeholder='Selecione...'/></SelectTrigger><SelectContent>{equipment.filter(e=>e.status==='available').map(e=><SelectItem key={e.id} value={e.id}>{e.code} - {e.name}</SelectItem>)}</SelectContent></Select></div>
<div><Label>Cliente</Label><Select value={rf.clientId} onValueChange={v=>setRf({...rf,clientId:v})}><SelectTrigger><SelectValue placeholder='Selecione...'/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>
<div><Label>Tipo</Label><Select value={rf.rentalType} onValueChange={v=>setRf({...rf,rentalType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='with_operator'>Com Operador</SelectItem><SelectItem value='without_operator'>Sem Operador</SelectItem></SelectContent></Select></div>
{rf.rentalType==='with_operator'&&<div><Label>Operador</Label><Select value={rf.operatorId} onValueChange={v=>{const em=employees.find((e:any)=>e.id===v);setRf({...rf,operatorId:v,operatorName:em?.name||''});}}><SelectTrigger><SelectValue placeholder='Selecione...'/></SelectTrigger><SelectContent>{employees.map((e:any)=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div>}
<div><Label>Faturamento</Label><Select value={rf.billingType} onValueChange={v=>setRf({...rf,billingType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='hourly'>Hora</SelectItem><SelectItem value='daily'>Dia</SelectItem><SelectItem value='monthly'>Mes</SelectItem><SelectItem value='fixed'>Fixo</SelectItem></SelectContent></Select></div>
<div><Label>Valor Unit (R$)</Label><Input type='number' value={rf.unitRate} onChange={e=>setRf({...rf,unitRate:e.target.value})}/></div>
<div><Label>Qtd</Label><Input type='number' value={rf.quantity} onChange={e=>setRf({...rf,quantity:e.target.value})}/></div>
<div><Label>Total: {fmt(Number(rf.unitRate||0)*Number(rf.quantity||1))}</Label></div>
<div><Label>Inicio</Label><Input type='date' value={rf.startDate} onChange={e=>setRf({...rf,startDate:e.target.value})}/></div>
<div><Label>Fim</Label><Input type='date' value={rf.endDate} onChange={e=>setRf({...rf,endDate:e.target.value})}/></div>
<div className='col-span-2'><Label>Endereco Entrega</Label><Input value={rf.deliveryAddress} onChange={e=>setRf({...rf,deliveryAddress:e.target.value})}/></div>
<div><Label>Cidade</Label><Input value={rf.deliveryCity} onChange={e=>setRf({...rf,deliveryCity:e.target.value})}/></div>
<div><Label>Estado</Label><Input value={rf.deliveryState} onChange={e=>setRf({...rf,deliveryState:e.target.value})}/></div>
<div className='col-span-2'><Label>Obs</Label><Textarea value={rf.notes} onChange={e=>setRf({...rf,notes:e.target.value})} rows={2}/></div>
</div><DialogFooter><Button variant='outline' onClick={()=>setRentDlg(false)}>Cancelar</Button><Button onClick={saveRent}>Criar</Button></DialogFooter></DialogContent></Dialog>
<Dialog open={maintDlg} onOpenChange={setMaintDlg}><DialogContent className='max-w-lg'><DialogHeader><DialogTitle>Nova Manutencao</DialogTitle></DialogHeader><div className='space-y-3'>
<div><Label>Equipamento *</Label><Select value={mf.equipmentId} onValueChange={v=>setMf({...mf,equipmentId:v})}><SelectTrigger><SelectValue placeholder='Selecione...'/></SelectTrigger><SelectContent>{equipment.map(e=><SelectItem key={e.id} value={e.id}>{e.code} - {e.name}</SelectItem>)}</SelectContent></Select></div>
<div><Label>Tipo</Label><Select value={mf.type} onValueChange={v=>setMf({...mf,type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='preventive'>Preventiva</SelectItem><SelectItem value='corrective'>Corretiva</SelectItem><SelectItem value='inspection'>Inspecao</SelectItem></SelectContent></Select></div>
<div><Label>Descricao *</Label><Input value={mf.description} onChange={e=>setMf({...mf,description:e.target.value})}/></div>
<div><Label>Custo (R$)</Label><Input type='number' value={mf.cost} onChange={e=>setMf({...mf,cost:e.target.value})}/></div>
<div><Label>Executado por</Label><Input value={mf.performedBy} onChange={e=>setMf({...mf,performedBy:e.target.value})}/></div>
<div><Label>Data</Label><Input type='date' value={mf.performedAt} onChange={e=>setMf({...mf,performedAt:e.target.value})}/></div>
<div><Label>Proxima</Label><Input type='date' value={mf.nextDueDate} onChange={e=>setMf({...mf,nextDueDate:e.target.value})}/></div>
<div><Label>Status</Label><Select value={mf.status} onValueChange={v=>setMf({...mf,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='scheduled'>Agendado</SelectItem><SelectItem value='in_progress'>Em Andamento</SelectItem><SelectItem value='completed'>Concluido</SelectItem></SelectContent></Select></div>
</div><DialogFooter><Button variant='outline' onClick={()=>setMaintDlg(false)}>Cancelar</Button><Button onClick={saveMaint}>Registrar</Button></DialogFooter></DialogContent></Dialog>
</div>);}
